apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    run: gitter
  name: gitter
spec:
  replicas: 1
  selector:
    run: gitter
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gitter
    spec:
      containers:
      - env:
        - name: DATAFOUNDRY_API_SERVER
          value: 10.1.1.x:443
        - name: GITHUB_CALLBACK_URL
          value: https://xxx.xxx.com/github_oauth_cb
        - name: GITHUB_CLIENT_ID
          value: xxxxxxxxxxxxxxx
        - name: GITHUB_CLIENT_SECRET
          value: xxxxxxxxxxxxxxx
        - name: GITLAB_APP_ID
          value: xxxxxxxxxxxxxxx
        - name: GITLAB_BASEURL
          value: https://gitlab.com
        - name: GITLAB_CALLBACK_URL
          value: https://xxx.xxx.com/gitlab_oauth_cb
        - name: GITLAB_CLIENT_SECRET
          value: xxxxxxxxxxxxxxx
        image: 10.1.1.x:5000/datafoundry/datafoundry-gitter
        imagePullPolicy: Always
        name: gitter
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
  
  ---
  
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: gitter
  name: gitter
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    run: gitter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
