apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    dadafoundry.io/image-datafoundryservicevolume: datafoundryservicevolume:latest
    dadafoundry.io/imageorisshow: ""
    dadafoundry.io/imageorpublic: "false"
    dadafoundry.io/last-replicas: "1"
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: datafoundryservicevolume
  name: datafoundryservicevolume
spec:
  replicas: 1
  selector:
    app: datafoundryservicevolume
    deploymentconfig: datafoundryservicevolume
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: datafoundryservicevolume
        deploymentconfig: datafoundryservicevolume
    spec:
      containers:
      - env:
        - name: DATAFOUNDRY_ADMIN_PASS
          value: "password"
        - name: DATAFOUNDRY_ADMIN_USER
          value: username
        - name: DATAFOUNDRY_HOST_ADDR
          value: 10.1.1.x:443
        - name: GLUSTER_ENDPOINTS_NAME
          value: glusterfs-cluster
        - name: HEKETI_HOST_ADDR
          value: 10.1.1.x
        - name: HEKETI_HOST_PORT
          value: "8080"
        - name: HEKETI_KEY
          value: passwordkey
        - name: HEKETI_USER
          value: admin
        - name: STORAGE_CLASS_NAME
          value: gluster-heketi
        - name: GLUSTER_VOLUME_REPLICA
          value: "3"
        image: 10.1.1.x:5000/datafoundry/datafoundryvolume
        imagePullPolicy: Always
        name: datafoundryservicevolume
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
  
  ---
  
  apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: datafoundryservicevolume
  name: datafoundryservicevolume
spec:
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app: datafoundryservicevolume
    deploymentconfig: datafoundryservicevolume
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
