apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: servicebroker-openshift
  name: servicebroker-openshift
spec:
  replicas: 1
  selector:
    app: servicebroker-openshift
    deploymentconfig: servicebroker-openshift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: servicebroker-openshift
        deploymentconfig: servicebroker-openshift
    spec:
      containers:
      - env:
        - name: BROKERPORT
          value: "8888"
        - name: CASSANDRAIMAGE
          value: 10.1.1.x:5000/service-brokers/cassandra-openshift-orchestration-3
        - name: DATAFOUNDRYPROXYADDR
          value: 172.25.x.x
        - name: DNSMASQ_SERVER
          value: 10.1.1.x
        - name: ELASTICSEARCHVOLUMEIMAGE
          value: 10.1.1.x:5000/service-brokers/elasticsearch
        - name: ENDPOINTSUFFIX
          value: xxx.xxx.xxx.com
        - name: ETCDBOOTIMAGE
          value: 10.1.1.x:5000/service-brokers/etcd-imported:v2.3.0
        - name: ETCDENDPOINT
          value: http://10.1.1.x:2379
        - name: ETCDIMAGE
          value: 10.1.1.x:5000/service-brokers/etcd-openshift-orchestration-2
        - name: ETCDPASSWORD
          value: etcdpassword
        - name: ETCDUSER
          value: etcdusername
        - name: ETCDVOLUMEIMAGE
          value: 10.1.1.x:5000/service-brokers/service-brokers-etcd-volumes
        - name: KAFKAIMAGE
          value: 10.1.1.x:5000/service-brokers/kafka-openshift-orchestration
        - name: KETTLEIMAGE
          value: 10.1.1.x:5000/service-brokers/kettle-service-2
        - name: MONGOVOLUMEIMAGE
          value: 10.1.1.x:5000/service-brokers/mongo-volumes
        - name: NIFIIMAGE
          value: 10.1.1.x:5000/service-brokers/nifi-imported
        - name: NODE_ADDRESSES
          value: 10.1.1.x,10.1.1.x,10.1.1.x
        - name: OPENSHIFTADDR
          value: 10.1.1.x:8443
        - name: OPENSHIFTPASS
          value: "password"
        - name: OPENSHIFTUSER
          value: username
        - name: PYSPIDERIMAGE
          value: 10.1.1.x:5000/service-brokers/pyspider
        - name: RABBITMQIMAGE
          value: 10.1.1.x:5000/service-brokers/service-brokers-rabbitmq-volumes
        - name: REDISIMAGE
          value: 10.1.1.x:5000/serviceborker/redis-openshift-2
        - name: REDISPHPADMINIMAGE
          value: 10.1.1.x:5000/service-brokers/php-redis-admin-imported
        - name: SBNAMESPACE
          value: service-brokers
        - name: SIMPLEFILEUPLOADERIMAGE
          value: 10.1.1.x:5000/service-brokers/simple-file-uploader
        - name: SPARKIMAGE
          value: 10.1.1.x:5000/service-brokers/spark-imported
        - name: STORMIMAGE
          value: 10.1.1.x:5000/service-brokers/storm-openshift-orchestration:v10_dep_dns
        - name: TENSORFLOWIMAGE
          value: 10.1.1.x:5000/service-brokers/tensorflow-imported:0.8.0123123
        - name: ZEPPLINIMAGE
          value: 10.1.1.x:5000/service-brokers/zepplin-imported
        - name: ZOOKEEPEREXHIBITORIMAGE
          value: 10.1.1.x:5000/service-brokers/zookeeper--envxhibitor-imported-2
        - name: ZOOKEEPERIMAGE
          value: 10.1.1.x:5000/service-brokers/zookeeper-openshift-orchestration
        - name: REDISCLUSTERIMAGE
          value: 10.1.1.x:5000/service-brokers/redis-sharding-node
        - name: REDISCLUSTERTRIBIMAGE
          value: 10.1.1.x:5000/service-brokers/redis-cluster-master:v3
        - name: KAFKAVOLUMEIMAGE
          value: 10.1.1.x:5000/service-brokers/service-brokers-kafka-volumes
        - name: NEO4JVOLUMEIMAGE
          value: 10.1.1.x:5000/service-brokers/neo4j
        - name: REDIS32IMAGE
          value: 10.1.1.x:5000/service-brokers/redis:3.2
        - name: NODE_DOMAINS
          value: nodex.xxx.com,nodex.xxx.com,nodex.xxx.com
        - name: STORMEXTERNALIMAGE
          value: 10.1.1.x:5000/service-brokers/storm:external
        - name: EXTERNALZOOKEEPERSERVERS
          value: 10.1.1.x,10.1.1.x,10.1.1.x
        - name: OCSP_OCM
          value: temp
        - name: OCSP_OCM_PORT
          value: temp
        - name: OCSP_HDP_VERSION
          value: temp
        - name: OCSPIMAGE
          value: temp
        - name: DATAIKUIMAGE
          value: 10.1.1.x:5000/dataiku/dataiku:latest
        - name: ANACONDAIMAGE
          value: 10.1.1.x:5000/anaconda3/anaconda3:v1
        image: 10.1.1.x:5000/service-brokers/servicebroker-openshift:latest
        imagePullPolicy: Always
        name: servicebroker-openshift
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: servicebroker-openshift
  name: servicebroker-openshift
spec:
  ports:
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: servicebroker-openshift
    deploymentconfig: servicebroker-openshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: datafoundryservicebrokeropenshift
  name: servicebroker
spec:
  host: xxx.xxx.xxx.com
  port:
    targetPort: 8888
  to:
    kind: Service
    name: servicebroker-openshift
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2017-11-06T08:16:55Z
      status: "True"
      type: Admitted
    host: xxx.xxx.xxx.com
    routerName: router
    wildcardPolicy: None
